# utils/pdf_generator.py
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
import textwrap
import hashlib
from typing import Dict, Any

def _write_wrapped(c, x, y, text, max_width=90, leading=12):
    """
    Helper to write wrapped text at (x,y). max_width is characters per line approx.
    """
    lines = textwrap.wrap(text, max_width)
    for i, line in enumerate(lines):
        c.drawString(x * mm, (y - i * (leading / 1.0)) * mm, line)
    return y - (len(lines) * (leading / 1.0))

def generate_report_pdf(report: Dict[str, Any], out_path: str):
    """
    Generate a readable PDF from the report dict.
    """
    c = canvas.Canvas(out_path, pagesize=A4)
    width, height = A4

    left_x = 15  # mm
    top_y = 280  # mm (approx)

    c.setFont("Helvetica-Bold", 14)
    c.drawString(left_x * mm, top_y * mm, "Claim Readiness Report")
    c.setFont("Helvetica", 9)
    c.drawString((left_x + 120) * mm, top_y * mm, f"Date: {report['summary'].get('report_date')}")

    y = top_y - 10
    # Patient / policy
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left_x * mm, y * mm, "Patient & Policy")
    c.setFont("Helvetica", 9)
    y -= 6
    c.drawString(left_x * mm, y * mm, f"Name: {report['summary'].get('patient_name')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Policy No: {report['summary'].get('policy_number')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Insurer (guessed): {report['summary'].get('insurer_guess')}")
    y -= 8

    # Hospital and diagnosis
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left_x * mm, y * mm, "Hospital & Diagnosis")
    c.setFont("Helvetica", 9)
    y -= 6
    c.drawString(left_x * mm, y * mm, f"Hospital: {report['summary'].get('hospital')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Admission: {report['summary'].get('admission_date')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Discharge: {report['summary'].get('discharge_date')}")
    y -= 5
    y = _write_wrapped(c, left_x, y - 2, f"Diagnosis: {report['summary'].get('diagnosis')}", max_width=110, leading=10)

    y -= 8
    # Financial summary
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left_x * mm, y * mm, "Financial Summary")
    c.setFont("Helvetica", 9)
    y -= 6
    fs = report.get("financial_summary", {})
    c.drawString(left_x * mm, y * mm, f"Total bill: ₹{fs.get('total_bill_amount')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Total payable (before co-pay): ₹{fs.get('total_payable_before_copay')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Co-pay: ₹{fs.get('co_pay_amount')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Insurance will pay (estimate): ₹{fs.get('final_insurance_payable')}")
    y -= 5
    c.drawString(left_x * mm, y * mm, f"Estimated user payable: ₹{fs.get('user_payable_estimate')}")
    y -= 8

    # Verdict & reasons
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left_x * mm, y * mm, "Verdict")
    c.setFont("Helvetica", 9)
    y -= 6
    y = _write_wrapped(c, left_x, y, f"{report.get('human_verdict')}", max_width=110, leading=10)
    y -= 6

    # Reasons and recommended actions
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left_x * mm, y * mm, "Reasons")
    c.setFont("Helvetica", 9)
    y -= 6
    for r in report.get("reasons", [])[:6]:
        y = _write_wrapped(c, left_x + 2, y, f"- {r}", max_width=110, leading=10)
        y -= 2

    y -= 6
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left_x * mm, y * mm, "Recommended Actions")
    c.setFont("Helvetica", 9)
    y -= 6
    for a in report.get("recommended_actions", [])[:6]:
        y = _write_wrapped(c, left_x + 2, y, f"- {a}", max_width=110, leading=10)
        y -= 2

    y -= 10
    # Missing documents
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left_x * mm, y * mm, "Missing Documents")
    c.setFont("Helvetica", 9)
    y -= 6
    for m in report.get("missing_documents", [])[:8]:
        c.drawString((left_x + 2) * mm, y * mm, f"- {m}")
        y -= 5

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(left_x * mm, 10 * mm, "Generated by Health Insurance Agent — demo. Verify with insurer before submission.")

    c.showPage()
    c.save()

    return out_path

def generate_claim_form_pdf(full_bill: Dict[str, Any], out_path: str):
    """
    Generate a simple pre-filled claim form PDF using known fields (patient, hospital, amounts).
    """
    c = canvas.Canvas(out_path, pagesize=A4)
    left_x = 15
    top_y = 280
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left_x * mm, top_y * mm, "Pre-filled Claim Form")

    y = top_y - 10
    c.setFont("Helvetica", 9)
    patient = full_bill.get("patient_details", {})
    hosp = full_bill.get("hospital_details", {})
    adm = full_bill.get("admission_details", {})
    billing = full_bill.get("billing_breakdown", {})

    c.drawString(left_x * mm, y * mm, f"Patient Name: {patient.get('patient_name')}")
    y -= 6
    c.drawString(left_x * mm, y * mm, f"Policy No: {patient.get('policy_number') or patient.get('insurance_id')}")
    y -= 6
    c.drawString(left_x * mm, y * mm, f"Hospital: {hosp.get('hospital_name')}")
    y -= 6
    c.drawString(left_x * mm, y * mm, f"Admission Date: {adm.get('admission_date')}")
    y -= 6
    c.drawString(left_x * mm, y * mm, f"Discharge Date: {adm.get('discharge_date')}")
    y -= 10
    # Financials
    total = billing.get("total_amount")
    c.drawString(left_x * mm, y * mm, f"Total Bill Amount (as per bill): ₹{total}")
    y -= 6
    c.drawString(left_x * mm, y * mm, "Claimant Signature: ____________________")
    y -= 20

    c.drawString(left_x * mm, y * mm, "Attach: Final bill, Discharge summary, Diagnostic reports, Pharmacy bills, Receipts")
    c.showPage()
    c.save()

    return out_path
